### ISSUE TITLE
AttributeError: 'module' object has not attribute 'scan'

### ISSUE THREAD

**Issue by kilickaya** [KnHuq/Dynamic-Tensorflow-Tutorial#3]
Hi,

I am trying to run the examples provided. However, it complains that tf module has no object 'scan'.  I am using Tensorflow version 0.7.1 installed via pip for Python 2.7

**Comment by KnHuq** [comment]
@kilickaya, Please update tensorflow. After that you will have will not face this problem. 
Please follow the link to update your tensorflow.
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation
