### ISSUE TITLE
Please help with Neural Stack Machine

### ISSUE THREAD

**Issue by arsenious** [KnHuq/Dynamic-Tensorflow-Tutorial#4]
Hi
Thank you very much for your tutorials. Please could you roughly tell how we can implemented the augmented memory module i.e. the neural stack of the Neural Stack Machine in tensorflow. I have understood the theory and I know how CNNs/RNNs/Autoencoders work in tensorflow but I'm unable to translate the augmented memory aspect into tensorflow.
Please help
Thank you

**Comment by KnHuq** [comment]
Dear arsenious,
Nice to know about your interest. Here are some resources you can follow: 
* https://iamtrask.github.io/2016/02/25/deepminds-neural-stack-machine/
* https://github.com/carpedm20/NTM-tensorflow

I am currently creating a tutorial on neural Turing machine and DNC. Please follow me on twitter or github to get the updates.
